@extends('core-themes.core-backpage')

@section('custom-css')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
<style>
.card{border:none;box-shadow:0 0 10px rgba(0,0,0,.05);border-radius:10px}.card-header{background:none;border-bottom:1px solid rgba(0,0,0,.05);padding:1.25rem 1.5rem}.card-body{padding:1.5rem}.table{margin-bottom:0}.table thead th{border-top:none;border-bottom:2px solid rgba(0,0,0,.05);font-weight:600;color:#6c757d;padding:.9rem .75rem}.table td{vertical-align:middle;padding:.75rem}.btn{border-radius:5px}.badge{padding:.5em .75em}
.table-responsive{width:100%;overflow-x:auto;overflow-y:visible;-webkit-overflow-scrolling:touch;scrollbar-width:thin}.table-responsive>.table{width:max-content;min-width:100%;margin-bottom:0}.table-responsive .table th,.table-responsive .table td{white-space:nowrap}.table-responsive .table .btn-group{display:inline-flex;flex-wrap:nowrap;white-space:nowrap}.table-responsive .table .btn{flex:0 0 auto}@media(max-width:768px){.table-responsive{margin-left:-.25rem;margin-right:-.25rem;width:calc(100% + .5rem)}.table-responsive>.table{min-width:760px}.table-responsive .table th,.table-responsive .table td{padding:.55rem .65rem;font-size:.875rem;vertical-align:middle}.table-responsive .table td[data-label]::before{content:none!important}.table-responsive .table .btn-group .btn{padding:.3rem .5rem}}
</style>
@endsection

@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-center mb-4"><div><h2 class="mb-1">Master Akademik</h2><div class="text-secondary">Data akademik kampus dan pengelolaan Mata Kuliah yang Anda ampu.</div></div><span class="badge bg-light-primary text-primary"><i class="fas fa-user-check me-1"></i>Dosen: {{ $user->name }}</span></div>
@if(session('success'))<div class="alert alert-success"><i class="fas fa-check-circle me-2"></i>{{ session('success') }}</div>@endif
@if(session('error'))<div class="alert alert-danger"><i class="fas fa-exclamation-circle me-2"></i>{{ session('error') }}</div>@endif
<div class="alert alert-info mb-4"><i class="fas fa-circle-info me-2"></i><strong>Hak akses:</strong> Anda dapat menambah, mengubah, dan menghapus hanya Mata Kuliah yang Anda ampu. Data master lainnya tetap menjadi referensi bersama.</div>

<div class="row mb-4">
@foreach([['Tahun Akademik',$taka->count(),'calendar-days'],['Fakultas',$fakultas->count(),'building-columns'],['Program Studi',$prodi->count(),'graduation-cap'],['Kurikulum',$kurikulum->count(),'book-open'],['Mata Kuliah Saya',$matakuliah->count(),'book'],['Kelas',$kelas->count(),'users'],['Jadwal Saya',$jadwal->count(),'calendar-check']] as $s)
<div class="col-6 col-md-4 col-xl mb-3"><div class="card h-100"><div class="card-body"><div class="d-flex align-items-center"><div><div class="text-secondary">{{ $s[0] }}</div><div class="h2 mb-0 mt-1">{{ $s[1] }}</div></div><div class="ms-auto text-primary"><i class="fas fa-{{ $s[2] }} fa-2x"></i></div></div></div></div></div>
@endforeach
</div>

<div class="card mb-4"><div class="card-header d-flex justify-content-between align-items-center"><h5 class="mb-0"><i class="fas fa-book me-2 text-primary"></i>Mata Kuliah yang Saya Ampu</h5><button class="btn btn-primary" data-bs-toggle="collapse" data-bs-target="#formTambahMk"><i class="fas fa-plus me-2"></i>Tambah Mata Kuliah</button></div><div class="card-body">
<div class="collapse mb-4" id="formTambahMk"><div class="card border"><div class="card-body"><h5 class="mb-3">Tambah Mata Kuliah Baru</h5><form action="{{ route('dosen.akademik.mata-kuliah.store') }}" method="POST" enctype="multipart/form-data">@csrf<div class="row">
<div class="col-md-6 mb-3"><label class="form-label">Nama Mata Kuliah</label><input name="name" class="form-control" required></div><div class="col-md-6 mb-3"><label class="form-label">Kurikulum</label><select name="kurikulum_id" class="form-select" required><option value="">Pilih Kurikulum</option>@foreach($kurikulum as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</select></div><div class="col-md-6 mb-3"><label class="form-label">Program Studi</label><select name="prodi_id" class="form-select" required><option value="">Pilih Program Studi</option>@foreach($prodi as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</select></div><div class="col-md-6 mb-3"><label class="form-label">Prasyarat</label><select name="requi_id" class="form-select"><option value="">Tidak ada</option>@foreach($matakuliah as $x)<option value="{{ $x->id }}">{{ $x->code }} - {{ $x->name }}</option>@endforeach</select></div><div class="col-md-4 mb-3"><label class="form-label">Semester</label><input type="number" name="semester" min="1" max="14" class="form-control" required></div><div class="col-md-4 mb-3"><label class="form-label">SKS</label><input name="bsks" class="form-control" required></div><div class="col-md-4 mb-3"><label class="form-label">Foto</label><input type="file" name="photo" class="form-control" accept="image/*"></div><div class="col-md-6 mb-3"><label class="form-label">RPS PDF</label><input type="file" name="docs_rps" class="form-control" accept=".pdf"></div><div class="col-md-6 mb-3"><label class="form-label">Kontrak Kuliah PDF</label><input type="file" name="docs_kontrak_kuliah" class="form-control" accept=".pdf"></div><div class="col-12 mb-3"><label class="form-label">Deskripsi</label><textarea name="desc" class="form-control" rows="3" required></textarea></div><div class="col-12 text-end"><button class="btn btn-primary"><i class="fas fa-save me-2"></i>Simpan</button></div></div></form></div></div></div>
<div class="table-responsive"><table class="table"><thead><tr><th class="text-center">No</th><th>Kode</th><th>Mata Kuliah</th><th>Program Studi</th><th>Kurikulum</th><th>Semester</th><th>SKS</th><th class="text-center">Aksi</th></tr></thead><tbody>
@forelse($matakuliah as $key=>$row)<tr><td data-label="No" class="text-center">{{ $key+1 }}</td><td data-label="Kode">{{ $row->code }}</td><td data-label="Mata Kuliah"><strong>{{ $row->name }}</strong></td><td data-label="Program Studi">{{ optional($row->programStudi)->name ?? '-' }}</td><td data-label="Kurikulum">{{ optional($row->kurikulum)->name ?? '-' }}</td><td data-label="Semester">{{ $row->semester }}</td><td data-label="SKS">{{ $row->bsks }}</td><td class="text-center"><div class="btn-group"><button class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#edit{{ $row->code }}"><i class="fas fa-edit"></i></button><form action="{{ route('dosen.akademik.mata-kuliah.delete',$row->code) }}" method="POST" onsubmit="return confirm('Hapus Mata Kuliah ini?')">@csrf @method('DELETE')<button class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></button></form></div></td></tr>@empty<tr><td colspan="8" class="text-center text-secondary py-4">Belum ada Mata Kuliah yang diampu.</td></tr>@endforelse
</tbody></table></div></div></div>

@foreach($matakuliah as $row)<div class="modal fade" id="edit{{ $row->code }}" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form action="{{ route('dosen.akademik.mata-kuliah.update',$row->code) }}" method="POST" enctype="multipart/form-data">@csrf @method('PATCH')<div class="modal-header"><h5 class="modal-title">Edit Mata Kuliah - {{ $row->name }}</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row"><div class="col-md-6 mb-3"><label class="form-label">Nama Mata Kuliah</label><input name="name" class="form-control" value="{{ $row->name }}" required></div><div class="col-md-6 mb-3"><label class="form-label">Kurikulum</label><select name="kurikulum_id" class="form-select" required>@foreach($kurikulum as $x)<option value="{{ $x->id }}" {{ $row->kurikulum_id==$x->id?'selected':'' }}>{{ $x->name }}</option>@endforeach</select></div><div class="col-md-6 mb-3"><label class="form-label">Program Studi</label><select name="prodi_id" class="form-select" required>@foreach($prodi as $x)<option value="{{ $x->id }}" {{ $row->prodi_id==$x->id?'selected':'' }}>{{ $x->name }}</option>@endforeach</select></div><div class="col-md-6 mb-3"><label class="form-label">Prasyarat</label><select name="requi_id" class="form-select"><option value="">Tidak ada</option>@foreach($matakuliah as $x)<option value="{{ $x->id }}" {{ $row->requi_id==$x->id?'selected':'' }}>{{ $x->code }} - {{ $x->name }}</option>@endforeach</select></div><div class="col-md-4 mb-3"><label class="form-label">Semester</label><input type="number" name="semester" min="1" max="14" class="form-control" value="{{ $row->semester }}" required></div><div class="col-md-4 mb-3"><label class="form-label">SKS</label><input name="bsks" class="form-control" value="{{ $row->bsks }}" required></div><div class="col-md-4 mb-3"><label class="form-label">Foto Baru</label><input type="file" name="photo" class="form-control" accept="image/*"></div><div class="col-md-6 mb-3"><label class="form-label">RPS Baru</label><input type="file" name="docs_rps" class="form-control" accept=".pdf"></div><div class="col-md-6 mb-3"><label class="form-label">Kontrak Kuliah Baru</label><input type="file" name="docs_kontrak_kuliah" class="form-control" accept=".pdf"></div><div class="col-12 mb-3"><label class="form-label">Deskripsi</label><textarea name="desc" class="form-control" rows="4" required>{{ $row->desc }}</textarea></div><div class="col-12"><div class="alert alert-light-primary mb-0"><i class="fas fa-lock me-2"></i>Penetapan Dosen dikunci. Anda hanya dapat mengelola mata kuliah yang tercatat sebagai mata kuliah Anda.</div></div></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary"><i class="fas fa-save me-2"></i>Simpan Perubahan</button></div></form></div></div></div>@endforeach

<div class="card"><div class="card-header"><h5 class="mb-0"><i class="fas fa-database me-2 text-info"></i>Referensi Akademik</h5></div><div class="card-body"><div class="row"><div class="col-md-4 mb-3"><strong>Fakultas</strong><div class="text-secondary">{{ $fakultas->count() }} data</div></div><div class="col-md-4 mb-3"><strong>Program Studi</strong><div class="text-secondary">{{ $prodi->count() }} data</div></div><div class="col-md-4 mb-3"><strong>Kurikulum</strong><div class="text-secondary">{{ $kurikulum->count() }} data</div></div><div class="col-md-4 mb-3"><strong>Jenis Kelas</strong><div class="text-secondary">{{ $jenisKelas->count() }} data</div></div><div class="col-md-4 mb-3"><strong>Kelas</strong><div class="text-secondary">{{ $kelas->count() }} data</div></div><div class="col-md-4 mb-3"><strong>Waktu Kuliah</strong><div class="text-secondary">{{ $waktuKuliah->count() }} data</div></div></div></div></div>
@endsection
